services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19132:19132"
      - "8123:8123"
    environment:
      TZ: "America/Los_Angeles"

      EULA: "TRUE"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "14G"
      USE_AIKAR_FLAGS: "true"

      TYPE: "paper"

      MOTD: "§dA Minecraft Server hosted on GitHub Actions :D"
      ONLINE_MODE: "false"
      DIFFICULTY: "peaceful"
      MAX_PLAYERS: "100"
      ENABLE_COMMAND_BLOCK: "true"
      MODE: "creative"
      ALLOW_FLIGHT: "true"

      RCON_PASSWORD: "minecraft" # totally secure password wow

      PLUGINS: |
        https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsXChat-2.20.1.jar
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.0.3/PAPER/ViaBackwards-5.0.3.jar
        https://cdn.modrinth.com/data/fRQREgAc/versions/AdtrWcU2/Dynmap-3.7-beta-7-spigot.jar
        https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-934.jar
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
      SPIGET_RESOURCES: "19254,52109,81534" # viaversion, viarewind, chunky
    volumes:
      - ./data:/data
