name: Runs Global

on: 
  workflow_dispatch:
    inputs:
      runNext:
        description: 'Should run next'
        required: true
        default: true
        type: boolean
      oldTailscaleHostname:
        description: 'Old Tailscale Hostname (not needed)'
        required: false
        default: ''
        type: string
 
permissions: write-all

jobs:
  custom:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        with:
          # pagekite doesn't work with >=3.12

          # the version that pagekite said in the docs was 2.7
          # but since setup-python removed 2.7 i have to use 3.11,
          # which surprisingly works
          python-version: '3.11'
      - name: Installs stuff
        run: |
          sudo apt update -y
          sudo apt install git wget docker-compose mosh -y
          curl -fsSL https://tailscale.com/install.sh | sh

          echo "$(whoami):password1!" | sudo chpasswd
          
          sudo tailscale up --hostname=global --advertise-exit-node --ssh --authkey ${{ secrets.TAILSCALE_KEY }}

          sed -i 's/unset .*//g' $HOME/.bashrc
          sed -i 's/#force_color_prompt/force_color_prompt/g' $HOME/.bashrc

          echo 'source $HOME/.bashrc' | sudo tee -a /etc/profile
      - name: Copy the files
        run: |
          sudo pkill provjobd

          cd /tmp
          wget -O archive.zip https://codeload.github.com/CeciliaKelley33Mm/CeciliaKelley33Mm.github.io/zip/refs/heads/main
          unzip archive.zip
      - name: Set everything up
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          CHANGE_COMMAND_USERNAME: ${{ secrets.CHANGE_COMMAND_USERNAME }}
          CHANGE_COMMAND_PASSWORD: ${{ secrets.CHANGE_COMMAND_PASSWORD }}
        run: |
          mkdir /tmp/muse
          cd /tmp/muse
          wget -O docker-compose.yml https://raw.githubusercontent.com/CeciliaKelley33Mm/global/refs/heads/master/muse-compose.yml
          sed -i 's/DISCORD_TOKEN_PLACEHOLDER/${{ secrets.DISCORD_TOKEN }}/g' docker-compose.yml
          sed -i 's/YOUTUBE_API_KEY_PLACEHOLDER/${{ secrets.YOUTUBE_API_KEY }}/g' docker-compose.yml
          sed -i 's/SPOTIFY_CLIENT_ID_PLACEHOLDER/${{ secrets.SPOTIFY_CLIENT_ID }}/g' docker-compose.yml
          sed -i 's/SPOTIFY_CLIENT_SECRET_PLACEHOLDER/${{ secrets.SPOTIFY_CLIENT_SECRET }}/g' docker-compose.yml
          docker compose up -d &

          if [ "${{ inputs.oldTailscaleHostname }}" != "" ]; then
            npm install -g serve

            cd /tmp

            aria2c -x 16 -j 16 -s 16 http://${{ inputs.oldTailscaleHostname }}:5000/archive.tar.gz

            tar xf archive.tar.gz

            cd minecraft
          else
            mkdir /tmp/minecraft
            cd /tmp/minecraft
            wget -O docker-compose.yml https://raw.githubusercontent.com/CeciliaKelley33Mm/global/refs/heads/master/minecraft-compose.yml
          fi
          docker compose up -d &

          cd /tmp/CeciliaKelley33Mm.github.io-main/backend
          npm i
          node index.js &
          
          curl -O https://pagekite.net/pk/pagekite.py
          wget https://raw.githubusercontent.com/CeciliaKelley33Mm/global/refs/heads/master/.pagekite.rc
          cp .pagekite.rc ~
          sed -i 's*KITENAMEPK*${{ secrets.KITENAME }}*g' ~/.pagekite.rc
          sed -i 's*KITESECRETPK*${{ secrets.KITESECRET }}*g' ~/.pagekite.rc
          python pagekite.py &

          wget https://raw.githubusercontent.com/CeciliaKelley33Mm/global/refs/heads/master/loop.sh
          chmod +x loop.sh
          bash loop.sh ${{ inputs.runNext }} $GH_TOKEN global runglobal.yml master global $WEBHOOK_URL true ${{ inputs.oldTailscaleHostname }}
